// This file was autogenerated by calcdeps.py
goog.addDependency("../../../coccyx/coccyx.js", ['coccyx'], ['coccyx.App']);
goog.addDependency("../../../coccyx/coccyxdeps.js", [], []);
goog.addDependency("../../../coccyx/app/app.js", ['coccyx.App'], ['coccyx.Router', 'coccyx.csrf', 'goog.net.XhrManager', 'goog.structs.Map']);
goog.addDependency("../../../coccyx/collection/collection.js", ['coccyx.Collection'], ['coccyx.Model', 'goog.array', 'goog.object', 'goog.pubsub.PubSub', 'goog.structs.Collection']);
goog.addDependency("../../../coccyx/collection/collection_test.js", [], ['coccyx', 'coccyx.Collection', 'coccyx.Model', 'coccyx.Repo', 'goog.testing.jsunit']);
goog.addDependency("../../../coccyx/controller/controller.js", ['coccyx.CollectionController', 'coccyx.Controller', 'coccyx.ModelController'], ['coccyx.Collection', 'coccyx.Model', 'coccyx.Repo', 'goog.async.Deferred', 'goog.events.EventHandler', 'goog.net.XhrManager']);
goog.addDependency("../../../coccyx/csrf/csrf.js", ['coccyx.csrf', 'coccyx.csrf.Adapter'], []);
goog.addDependency("../../../coccyx/csrf/rails.js", ['coccyx.csrf.RailsAdapter'], ['coccyx.csrf']);
goog.addDependency("../../../coccyx/model/model.js", ['coccyx.Model', 'coccyx.Model.Topics'], ['goog.array', 'goog.object', 'goog.pubsub.PubSub', 'goog.string', 'goog.ui.IdGenerator']);
goog.addDependency("../../../coccyx/net/extendedhttpstatus.js", ['coccyx.net.ExtendedHttpStatus'], []);
goog.addDependency("../../../coccyx/repo/remoterepo.js", ['coccyx.RemoteRepo'], ['coccyx.Model', 'coccyx.Repo', 'coccyx.csrf', 'goog.async.Deferred', 'goog.debug.Logger', 'goog.net.XhrManager']);
goog.addDependency("../../../coccyx/repo/repo.js", ['coccyx.Repo'], ['coccyx.Collection', 'coccyx.Model', 'goog.async.Deferred']);
goog.addDependency("../../../coccyx/router/route.js", ['coccyx.Route', 'coccyx.RouteMatch', 'coccyx.RouteMatcher'], ['coccyx.Model', 'coccyx.RouteRegExp', 'goog.array', 'goog.object', 'goog.pubsub.PubSub', 'goog.string.format']);
goog.addDependency("../../../coccyx/router/route_test.js", [], ['coccyx', 'coccyx.Route', 'coccyx.RouteRegExp', 'coccyx.Router', 'goog.Uri', 'goog.string', 'goog.testing.jsunit']);
goog.addDependency("../../../coccyx/router/router.js", ['coccyx.Router'], ['coccyx.Route', 'goog.Uri', 'goog.debug.Logger', 'goog.pubsub.PubSub', 'goog.userAgent']);
goog.addDependency("../../../coccyx/router/routeregexp.js", ['coccyx.RouteRegExp'], ['coccyx.Model']);
goog.addDependency("../../../coccyx/string/string.js", ['coccyx.string'], []);
goog.addDependency("../../../coccyx/view/view.js", ['coccyx.View'], ['coccyx.Collection', 'coccyx.Model', 'goog.ui.Component']);
