goog.provide('coccyx.net.ExtendedHttpStatus');


/**
 * Extended HTTP Status codes, as defined by various RFCs and actual usage.
 * @see http://en.wikipedia.org/wiki/List_of_HTTP_status_codes
 * @see {goog.net.HttpStatus}
 * @enum {number}
 */
coccyx.net.ExtendedHttpStatus = {
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  RESUME_INCOMPLETE: 308,

  IM_A_TEAPOT: 418,
  ENHACE_YOUR_CALM: 420,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  UNORDERED_COLLECTION: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  NO_RESPONSE: 444,
  RETRY_WITH: 449,
  BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS: 450,
  CLIENT_CLOSED_REQUEST: 499,

  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  NETWORK_READ_TIMEOUT_ERROR: 598,
  NETWORK_CONNECT_TIMEOUT_ERROR: 599
};
